Incorporate the rules script into AppRun and separate rules file

diff --git a/installer-assets/appimage/AppRun b/installer-assets/appimage/AppRun
--- a/installer-assets/appimage/AppRun
+++ b/installer-assets/appimage/AppRun
@@ -2,18 +2,85 @@
 
 set -e
 
-this_dir="$(readlink -f "$(dirname "$0")")"
+THIS_DIR="$(readlink -f "$(dirname "$0")")"
+
+RULES_FILE='42-flipperzero.rules'
+RULES_DIR=${3:-'/etc/udev/rules.d'}
+TARGET_RULES_PATH="$RULES_DIR/$RULES_FILE"
+SOURCE_RULES_PATH="$THIS_DIR/usr/lib/udev/rules.d/$RULES_FILE"
+
+SUDO_MESSAGE='You will now be asked for SUDO password.\n'
+
+check_rules_dir() {
+    if ! [ -d "$RULES_DIR" ]; then
+        printf "Error: directory \"$RULES_DIR\" does not exist.\n"
+        exit 255
+    fi
+}
+
+install_udev_rules() {
+    check_rules_dir
+
+    if [ -f "$TARGET_RULES_PATH" ]; then
+        printf 'The rules have already been installed. Bye!\n'
+        exit
+    fi
+
+    printf "$SUDO_MESSAGE"
+
+    # The danger zone
+    if \
+        sudo -K \
+        && sudo cp "$SOURCE_RULES_PATH" "$TARGET_RULES_PATH" \
+        && sudo udevadm control --reload-rules \
+        && sudo udevadm trigger
+    # End of danger zone
+    then
+        printf "Device rules have been installed successfully. You're good to go!\n"
+    else
+        printf "Something went wrong. Device rules may have not been installed correctly.\n"
+    fi
+}
+
+uninstall_udev_rules() {
+    check_rules_dir
+
+    if ! [ -f "$RULES_FILE" ]; then
+        printf 'Nothing to uninstall. Bye!\n'
+        exit
+    fi
+
+    printf "$SUDO_MESSAGE"
+
+    # The danger zone
+    if
+        sudo -K \
+        && sudo rm -rf "$TARGET_RULES_PATH" \
+        && sudo udevadm control --reload-rules \
+        && sudo udevadm trigger
+    # End of danger zone
+    then
+        printf "Device rules have been uninstalled successfully. Thank you.\n"
+    else
+        printf "Something went wrong. Device rules may have not been uninstalled correctly.\n"
+    fi
+}
 
 if [[ $# -eq 0 ]]; then
-    "$this_dir"/usr/bin/qFlipper
+    "$THIS_DIR"/usr/bin/qFlipper
 elif [[ "$1" = 'gui' ]]; then
     shift 1
-    "$this_dir"/usr/bin/qFlipper "$@"
+    "$THIS_DIR"/usr/bin/qFlipper "$@"
 elif [[ "$1" = 'cli' ]]; then
     shift 1
-    "$this_dir"/usr/bin/qFlipper-cli "$@"
+    "$THIS_DIR"/usr/bin/qFlipper-cli "$@"
+elif [[ "$1" = 'rules' ]]; then
+    case "$2" in
+        'install') install_udev_rules ;;
+        'uninstall') uninstall_udev_rules ;;
+        *) printf "Usage: $APPIMAGE rules {install, uninstall} [/path/to/rules.d]\n"; exit 255 ;;
+    esac
 else
-    echo 'Usage: <Appimage> {[gui], cli} [parameters]'
+    printf "Usage: $APPIMAGE {[gui], cli, rules} [parameters]\n"
     exit 255
 fi
-
